### ISSUE TITLE
adding file breaks during git p4 submit on Windows

### ISSUE THREAD

**Issue by dbiollo** [ermshiperete/git-p4#10]
There is a problem when running "git p4 submit" on Windows, if the commit you are pushing to P4 contains a _new_ file. I'm not sure if this bug happens on Mac/Linux but I doubt it -- seems to be related to backslash.

Below is the error stack that I got from the --verbose option. It's dying while trying to get the file type of a newly added p4 file.

After some debugging of the git-p4 python script, I found that backslashes (found in self.clientPath) are interpreted as escapes on line 295 when shlex.split(c) is called -- this totally mangles otherwise valid parameters to p4.

(I blanked out the full code path with underscores, otherwise, here is the stack)

Path 'C:C:\Code________' is not under client's root 'C:\Code'.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 2403, in <module>
    main()
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 2398, in main
    if not cmd.run(args):
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 1130, in run
    self.applyCommits()
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 1075, in applyCommits
    self.applyCommit(commit)
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 1055, in applyCommit
    self.setExecutableBits()
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 927, in setExecutableBits
    self.p4.setP4ExecBit(os.path.join(self.clientPath, f), mode)
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 130, in setP4ExecBit
    p4Type = self.getP4OpenedType(file)
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 141, in getP4OpenedType
    result = self.p4_read_pipe("opened %s" % file)
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 110, in p4_read_pipe
    return read_pipe(real_cmd, ignore_error)
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 298, in read_pipe
    die('Command failed: %s' % c)
  File "C:\Program Files (x86)\Git/libexec/git-core/git-p4", line 23, in die
    raise Exception(msg)
Exception: Command failed: p4 -d _____________________ opened ____________

**Comment by dbiollo** [comment]
I'd like to propose this fix, which has worked for me - changing the backslashes to forward slashes.

@1107:
        self.clientPath = self.p4.p4Where(self.depotPath)
        if self.isWindows:
            self.clientPath = self.clientPath.replace("\", "/")

FYI ... my machine is Windows 7, 64bit, with Python 2.7.2
